name: ex-rates
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Update ExRates
        run: |
          curl -v --request POST \
          --url 'https://www.inverse.finance/api/cron-ex-rates' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
