name: 10-minute-blog-cron
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Revalidation by GET until nextjs update
        run: |
          curl -v --request GET \
          --url 'https://www.inverse.finance/blog/en-US'
